import { processComponent } from "./processComponent.js";

const DataGrid = {
	type: "datagrid",
	label: "",
  reorder: false,
  addAnotherPosition: "bottom",
  layoutFixed: true,
  enableRowGroups: false,
  initEmpty: false,
  tableView: false,
	input: true,
	defaultValue: [{}],
};
const Columns = [
	{
		key: "service",
		label: "Service name",
		type: "textfield",
	},
	{
		key: "frequency",
		label: "Frequency (e.g. daily, monthly, quarterly, as needed)",
		type: "textfield",
	},
	{
		key: "served",
		label: "Number of people served during reporting period",
		type: "number",
	},
];

const description = (examples) => `e.g. ${examples}`;
const label = (name, desc) => name[0].toUpperCase() + name.slice(1) + (desc ? `<br>(${description(desc)})` : "");

export function serviceOffering(
	data,
	context)
{
	const { uniqueKey } = context;
	const { name, examples, required, key = uniqueKey(name.split(/\W+/).slice(-5).join(" ")) } = data;
	const serviceCheckbox = {
		type: "checkbox",
		key,
		label: label(name, examples),
		required,
	};
	const serviceGrid = {
		...DataGrid,
		key: key + "_grid",
		customClass: "service-grid",
		hideLabel: true,
			// force the key to be what is specified above, rather than being autogenerated
		components: Columns.map((column) => ({ ...processComponent(column, context), key: column.key })),
		conditional: {
			show: true,
			when: key,
			eq: true,
		}
	};

	return [
		serviceCheckbox,
		serviceGrid
	];
}
